version: '3'

services:
  shortener-url:
    container_name: url-shortener
    build:
      context: ./
      dockerfile: Dockerfile
    mem_reservation: 700m
    ports:
      - "8085:8085"
    networks:
      - "url-shortener-network"
    depends_on:
      - zk1
      - master
      - cassandra


  cassandra:
    container_name: cassandra
    restart: always
    image: cassandra
    ports:
      - 9042:9042

  master:
    container_name: master
    image: "redis:alpine"
    ports:
      - "6379:6379"
  slave-1:
      container_name: slave-1
      image: "redis:alpine"
      ports:
        - "16379:6379"
  slave-2:
      container_name: slave-2
      image: "redis:alpine"
      ports:
        - 26379:6379
  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=master:master,slave-1:slave-1,slave-2:slave-2
      ports:
        - "8081:8081"

  zk1:
    container_name: zk1
    hostname: zk1
    image: bitnami/zookeeper:3.6.2
    ports:
      - 2181:2181
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_SERVER_ID=1
     - ZOO_SERVERS=0.0.0.0:2888:3888,zk2:2888:3888,zk3:2888:3888
    networks:
      - "url-shortener-network"
  zk2:
    container_name: zk2
    hostname: zk2
    image: bitnami/zookeeper:3.6.2
    ports:
      - 2182:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zk1:2888:3888,0.0.0.0:2888:3888,zk3:2888:3888
    networks:
      - "url-shortener-network"
  zk3:
    container_name: zk3
    hostname: zk3
    image: bitnami/zookeeper:3.6.2
    ports:
      - 2183:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zk1:2888:3888,zk2:2888:3888,0.0.0.0:2888:3888
    networks:
          - "url-shortener-network"
  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator
    ports:
      - 7000:9000
    networks:
      - "url-shortener-network"



networks:
  url-shortener-network:
